TypeError:
  At type.py, line 4, in __init__()
